// src/components/UserList/index.tsx
import React from 'react';

import { Container, Role, User, Avatar } from './styles';

interface UserProps {
  nickname: string;
  isBot?: boolean;
}

const UserRow: React.FC<UserProps> = ({ nickname, isBot }) => {
  return (
    <User>
      <Avatar className={isBot ? 'bot' : ''} />

      <strong>{nickname}</strong>

      {isBot && <span>Bot</span>}
    </User>
  );
};

const UserList: React.FC = () => {
  return (
    <Container>
      <Role>Disponível - 1</Role>
      <UserRow nickname="Roger Luiz" />

      <Role>Offline - 18</Role>
      <UserRow nickname="Renato Maia" isBot />
      <UserRow nickname="Fulano" />
      <UserRow nickname="Fulano" />
      <UserRow nickname="Fulano" />
      <UserRow nickname="Fulano" />
      <UserRow nickname="Fulano" />
      <UserRow nickname="Fulano" />
      <UserRow nickname="Fulano" />
      <UserRow nickname="Fulano" />
      <UserRow nickname="Fulano" />
      <UserRow nickname="Fulano" />
      <UserRow nickname="Fulano" />
      <UserRow nickname="Fulano" />
      <UserRow nickname="Fulano" />
      <UserRow nickname="Fulano" />
      <UserRow nickname="Fulano" />
      <UserRow nickname="Fulano" />
      <UserRow nickname="Fulano" />
    </Container>
  );
};

export default UserList;

// src/components/UserList/UserList.vue
<template>
  <div class="container-UserList">
    <div class="role">Disponível - 2</div>
    <UserRow isBot nickname="Jirem"/>
    <UserRow nickname="Roger"/>
    <div class="role">Offline - 18</div>
    <UserRow nickname="Luiz" v-for="user in 18" :key="user.id"/>
  </div>
</template>

<script>
  import UserRow from './UserRow/UserRow.vue'

  export default {
    components: {
      UserRow
    }
  }
</script>

<style src="./style.scss" lang="scss" scoped></style>
