// src/components/ServerButton/index.tsx
import React from 'react';

import Logo from '../../assets/Logo.svg';

import { Button } from './styles';

export interface Props {
  selected?: boolean;
  isHome?: boolean;
  hasNotifications?: boolean;
  mentions?: number;
}

const ServerButton: React.FC<Props> = ({
  selected,
  isHome,
  hasNotifications,
  mentions,
}) => {
  return (
    <Button
      isHome={isHome}
      hasNotifications={hasNotifications}
      mentions={mentions}
      className={selected ? 'active' : ''}
    >
      {isHome && <img src={Logo} alt="Logo" />}
    </Button>
  );
};

export default ServerButton;

// src/components/ServerList/ServerButton/ServerButton.vue
<template>
  <div class="container-serverButton" :class="{ 'serverButton-isHome':isHome, 'serverButton-hasNotification':hasNotification }">

    <img src="../../../assets/discord.svg" v-if="isHome">
    <div class="mentions" v-if="mentions"> {{ mentions }} </div>
  </div>
</template>

<script>
  export default {
    props: {
      selected: Boolean,
      isHome: Boolean,
      hasNotification: Boolean,
      mentions: Number
    }
  }
</script>

<style src="./style.scss" lang="scss" scoped></style>
